version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=inixr_site.settings
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  static_volume:
  media_volume:

