# Generated by Django 5.2.2 on 2025-06-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('AR', 'Augmented Reality'), ('VR', 'Virtual Reality'), ('XR', 'Extended Reality')], max_length=20)),
                ('description', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('amazon_link', models.URLField(blank=True, null=True)),
                ('flipkart_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Beta', 'Beta'), ('Production', 'Production'), ('Coming Soon', 'Coming Soon')], default='Production', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
