# Generated by Django 5.1.3 on 2025-06-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_partnership_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='amazon_link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='flipkart_link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='partnership_details',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='show_direct_purchase',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='usage',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PurchaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('button_color', models.CharField(default='blue', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_links', to='portfolio.portfolio')),
            ],
        ),
    ]
