# Generated by Django 5.1.3 on 2025-06-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_amazon_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
    ]
