# Generated by Django 5.1.3 on 2025-06-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='video_file',
            new_name='video',
        ),
    ]
