# Generated by Django 5.2.2 on 2026-09-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('open', 'Link opened'), ('start', 'Tapped open gift'), ('song_done', 'Song finished'), ('mic_ok', 'Mic allowed'), ('mic_denied', 'Mic denied'), ('blown', 'Candles blown out'), ('room', 'Room view'), ('replay', 'Replay'), ('send_back', 'Tapped send wish back'), ('create_open', 'Creator opened'), ('link_created', 'Wish link created'), ('wa_share', 'Shared to WhatsApp'), ('copy', 'Copied link')], db_index=True, max_length=24)),
                ('wid', models.CharField(blank=True, db_index=True, max_length=12)),
                ('ref', models.CharField(blank=True, db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
