# Generated by Django 5.2.2 on 2026-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_wishevent_kind_alter_wishevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishevent',
            name='event',
            field=models.CharField(choices=[('open', 'Link opened'), ('start', 'Tapped open gift'), ('cam_ok', 'Camera allowed'), ('cam_denied', 'Camera denied'), ('lit', 'Lit the candles'), ('song_done', 'Song finished'), ('mic_ok', 'Mic allowed'), ('mic_denied', 'Mic denied'), ('blown', 'Candles blown out'), ('gift_open', 'Opened thank-you gift'), ('heart_pop', 'Popped a heart'), ('room', 'Room view'), ('selfie', 'Selfie view'), ('photo', 'Took photo'), ('photo_share', 'Shared photo'), ('video', 'Recorded video'), ('video_share', 'Shared video'), ('replay', 'Replay'), ('send_back', 'Tapped say thank you'), ('create_open', 'Creator opened'), ('link_created', 'Wish link created'), ('wa_share', 'Shared to WhatsApp'), ('copy', 'Copied link')], db_index=True, max_length=24),
        ),
    ]
