# Generated by Django 5.2.2 on 2026-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0004_alter_wishevent_event_alter_wishevent_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishevent',
            name='kind',
            field=models.CharField(blank=True, choices=[('bday', 'Birthday'), ('ty', 'Thank you'), ('rx', 'Reaction'), ('aw', 'Award')], db_index=True, max_length=8),
        ),
    ]
